Elevator rework
Salt-Grain-Studio/WobblyStealthGame pull request #145
Opened 2021-11-18 10:57 UTC by ronanhub

2021-11-18 14:38 UTC, Jarivanoort requested changes

2021-11-18 14:38 UTC, Jarivanoort commented on WobblyStealthGame/Assets/Scripts/Interactables/Elevator.cs
> +            foreach(Vector3 position in positions)
```suggestion
            foreach (Vector3 position in positions)
```

2021-11-18 14:45 UTC, Jarivanoort approved these changes

2021-11-19 09:58 UTC, ahoefnagel requested changes

2021-11-19 09:58 UTC, ahoefnagel commented on WobblyStealthGame/Assets/Scripts/Interactables/Elevator.cs
> +        topShaft.localScale = new Vector3(topShaft.localScale.x, (transform.position.y - positions[positions.Length-1].y), topShaft.localScale.z);
```suggestion
        bottomShaft.position = new Vector3(bottomShaft.position.x, (positions[0].y + transform.position.y) / 2, bottomShaft.position.z);
        bottomShaft.localScale = new Vector3(bottomShaft.localScale.x, (positions[0].y - transform.position.y), bottomShaft.localScale.z);
        topShaft.position = new Vector3(topShaft.position.x, (positions[positions.Length-1].y + elevatorHeight.position.y + 2) / 2, topShaft.position.z);
        topShaft.localScale = new Vector3(topShaft.localScale.x, (transform.position.y - positions[positions.Length-1].y), topShaft.localScale.z);
```

2021-11-19 09:58 UTC, ahoefnagel commented on WobblyStealthGame/Assets/Scripts/Interactables/Elevator.cs
> +                Gizmos.DrawWireSphere(transform.position+position, 0.25f);
```suggestion
                Gizmos.DrawWireSphere(transform.position + position, 0.25f);
```

2021-11-19 11:15 UTC, MatthijsHofele approved these changes

2021-11-19 11:40 UTC, merged

2021-11-19 11:40 UTC, ahoefnagel approved these changes