trampoline
Salt-Grain-Studio/WobblyStealthGame pull request #151
Opened 2021-11-18 14:57 UTC by ronanhub

2021-11-18 15:04 UTC, Jarivanoort requested changes

2021-11-18 15:04 UTC, Jarivanoort commented on WobblyStealthGame/Assets/Scripts/Interactables/ExtraBounciness.cs
> +        collision.collider.GetComponent<Rigidbody>().AddForce(Vector3.up * Mathf.Abs(collision.relativeVelocity.magnitude)*forceMultiplier, ForceMode.Impulse);
```suggestion
        collision.collider.GetComponent<Rigidbody>().AddForce(Vector3.up * Mathf.Abs(collision.relativeVelocity.magnitude) * forceMultiplier, ForceMode.Impulse);
```

2021-11-19 10:04 UTC, ahoefnagel requested changes

2021-11-19 10:04 UTC, ahoefnagel commented on WobblyStealthGame/Assets/Scripts/Interactables/ExtraBounciness.cs
> +    }
```suggestion
    void OnCollisionEnter(Collision collision) =>
        collision.collider.GetComponent<Rigidbody>().AddForce(Vector3.up * Mathf.Abs(collision.relativeVelocity.magnitude) * forceMultiplier, ForceMode.Impulse);
```

2021-11-19 11:41 UTC, ahoefnagel approved these changes

2021-11-19 15:38 UTC, Jarivanoort approved these changes

2021-11-19 15:38 UTC, merged