Micromanagement arm movement
Salt-Grain-Studio/WobblyStealthGame pull request #153
Opened 2021-11-18 21:33 UTC by MatthijsHofele

2021-11-18 21:52 UTC, ahoefnagel requested changes

2021-11-18 21:52 UTC, ahoefnagel commented on WobblyStealthGame/Assets/Scripts/Input/ActiveRagdoll/PlayerController.cs
> +    [SerializeField] public GameObject HandR;
```suggestion
    public GameObject HandLeft;
    public GameObject HandRight;
```

2021-11-18 21:52 UTC, ahoefnagel commented on WobblyStealthGame/Assets/Scripts/Input/ActiveRagdoll/GrabModule.cs
> +	private bool hasJoint;
```suggestion
    private bool hasJoint;
```

2021-11-18 21:52 UTC, ahoefnagel commented on WobblyStealthGame/Assets/HandIk.cs
> +    public Transform leftHandObj = null;
These two properties aren't used outside of this class. Shouldn't they be private? if not they require to follow PascalCase.

2021-11-18 21:52 UTC, ahoefnagel commented on WobblyStealthGame/Assets/HandIk.cs
> +    public static bool ikActiveRight = false;
```suggestion
    public static bool IkActiveLeft = false;
    public static bool IkActiveRight = false;
```

2021-11-18 21:52 UTC, ahoefnagel commented on WobblyStealthGame/Assets/HandIk.cs
> +            if (ikActiveLeft)
```suggestion
            if (IkActiveLeft) 
```

2021-11-18 21:52 UTC, ahoefnagel commented on WobblyStealthGame/Assets/HandIk.cs
> +            if (ikActiveRight)
```suggestion
            if (IkActiveRight)
```

2021-11-18 21:52 UTC, ahoefnagel commented on WobblyStealthGame/Assets/HandIk.cs
> +                    animator.SetIKRotation(AvatarIKGoal.LeftHand,leftHandObj.rotation);
```suggestion
                    animator.SetIKPosition(AvatarIKGoal.LeftHand, leftHandObj.position);
                    animator.SetIKRotation(AvatarIKGoal.LeftHand, leftHandObj.rotation);
```

2021-11-18 21:52 UTC, ahoefnagel commented on WobblyStealthGame/Assets/HandIk.cs
> +                    animator.SetIKRotation(AvatarIKGoal.RightHand,rightHandObj.rotation);
```suggestion
                    animator.SetIKPosition(AvatarIKGoal.RightHand, rightHandObj.position);
                    animator.SetIKRotation(AvatarIKGoal.RightHand, rightHandObj.rotation);
```

2021-11-18 21:52 UTC, ahoefnagel commented on WobblyStealthGame/Assets/Scripts/Input/ActiveRagdoll/InputModule.cs
> +        HandIk.ikActiveLeft = !HandIk.ikActiveLeft;
```suggestion
        HandIk.IkActiveLeft = !HandIk.IkActiveLeft;
```

2021-11-18 21:52 UTC, ahoefnagel commented on WobblyStealthGame/Assets/Scripts/Input/ActiveRagdoll/InputModule.cs
> +        HandIk.ikActiveRight = !HandIk.ikActiveRight;
```suggestion
        HandIk.IkActiveRight = !HandIk.IkActiveRight;
```

2021-11-18 21:52 UTC, ahoefnagel commented on WobblyStealthGame/Assets/Scripts/Input/ActiveRagdoll/GrabModule.cs
> +    	if (!grabbing || hasJoint || collision.gameObject.name == "CameraCollider" || (!collision.gameObject.GetComponent<BoxCollider>() && !collision.gameObject.GetComponent<CapsuleCollider>()) && !col
```suggestion
    	if (!grabbing || hasJoint || collision.gameObject.name == "CameraCollider" || (!collision.gameObject.GetComponent<BoxCollider>() && !collision.gameObject.GetComponent<CapsuleCollider>()) && !collision.gameObject.GetComponent<MeshCollider>().convex) 
    	{
            return;
        }
```

2021-11-18 21:52 UTC, ahoefnagel commented on WobblyStealthGame/Assets/Scripts/Input/ActiveRagdoll/GrabModule.cs
> +            if (holdingItem && holdingItem.GetComponent<FixedJoint>()) Destroy(holdingItem.GetComponent<FixedJoint>());
```suggestion
            if (holdingItem && holdingItem.GetComponent<FixedJoint>()) 
            {
                Destroy(holdingItem.GetComponent<FixedJoint>());
            }
```

2021-11-18 22:32 UTC, ahoefnagel approved these changes

2021-11-19 10:04 UTC, ahoefnagel approved these changes

2021-11-19 10:11 UTC, SjonsDePlons approved these changes

2021-11-19 11:20 UTC, merged