Add: springiness array
Salt-Grain-Studio/WobblyStealthGame pull request #159
Opened 2021-11-19 15:49 UTC by SjonsDePlons

Made 2 array's which saves the springiness. This is used to reset the springiness if you have set it to 0

2021-11-19 15:59 UTC, Jarivanoort requested changes
Grab animatie werkt niet meer en er staan nog allemaal debug logs

2021-11-19 17:59 UTC, MatthijsHofele approved these changes

2021-11-22 09:30 UTC, Jarivanoort approved these changes

2021-11-22 09:32 UTC, ronanhub commented on WobblyStealthGame/Assets/Scripts/Input/ActiveRagdoll/PlayerController.cs
> +    public float[] yzDriveSpringiness;
```suggestion
    public float[] XDriveSpringiness;
    public float[] YZDriveSpringiness;
```

2021-11-22 09:32 UTC, ronanhub commented on WobblyStealthGame/Assets/Scripts/Input/ActiveRagdoll/PlayerController.cs
> +        yzDriveSpringiness = new float[Joints.Length];
```suggestion
        XDriveSpringiness = new float[Joints.Length];
        YZDriveSpringiness = new float[Joints.Length];
```

2021-11-22 09:32 UTC, ronanhub commented on WobblyStealthGame/Assets/Scripts/Input/ActiveRagdoll/PlayerController.cs
> +            yzDriveSpringiness[i] = Joints[i].angularYZDrive.positionSpring;
```suggestion
            XDriveSpringiness[i] = Joints[i].angularXDrive.positionSpring;
            YZDriveSpringiness[i] = Joints[i].angularYZDrive.positionSpring;
```

2021-11-22 09:33 UTC, ahoefnagel requested changes

2021-11-22 09:33 UTC, ahoefnagel commented on WobblyStealthGame/Assets/Scripts/Input/ActiveRagdoll/BalanceModule.cs
> +                jointDriveX.positionSpring = PlayerController.xDriveSpringiness[i];
```suggestion
                jointDriveX.positionSpring = PlayerController.XDriveSpringiness[i];
```

2021-11-22 09:33 UTC, ahoefnagel commented on WobblyStealthGame/Assets/Scripts/Input/ActiveRagdoll/BalanceModule.cs
> +                jointDriveYZ.positionSpring = PlayerController.yzDriveSpringiness[i];
```suggestion
                jointDriveYZ.positionSpring = PlayerController.YZDriveSpringiness[i];
```

2021-11-22 09:42 UTC, ahoefnagel approved these changes

2021-11-22 09:43 UTC, merged