Added sound to beam animation
Salt-Grain-Studio/WobblyStealthGame pull request #169
Opened 2021-11-22 12:35 UTC by MugZitch

2021-11-22 12:41 UTC, ronanhub requested changes
alles werkt maar de code conventions kloppen nog niet

2021-11-22 12:41 UTC, ronanhub commented on WobblyStealthGame/Assets/Art/Fbx/Beam/Beam.cs
> +
```suggestion
```

2021-11-22 12:41 UTC, ronanhub commented on WobblyStealthGame/Assets/Art/Fbx/Beam/Beam.cs
> +            audioSource.Stop();
```suggestion
        if (playAnimation)
        {
            audioSource.Play();
        }
        else
        {
            audioSource.Stop();
        }
```

2021-11-22 12:41 UTC, ronanhub commented on WobblyStealthGame/Assets/Art/Fbx/Beam/Beam.cs
> +    public AudioSource audioSource;
```suggestion
    private Animator animator;
    private AudioSource audioSource;
```

2021-11-23 10:20 UTC, MatthijsHofele requested changes
@ronanhub where sound

2021-11-23 10:23 UTC, ronanhub commented
> @ronanhub where sound

¯\_(ツ)_/¯

2021-11-23 10:28 UTC, ronanhub commented
"added beam sound to prefab"
There sound

2021-11-23 10:43 UTC, MatthijsHofele approved these changes
yes sound good

2021-11-23 10:55 UTC, merged