Add: Better dive with double space press
Salt-Grain-Studio/WobblyStealthGame pull request #185
Opened 2021-11-24 12:58 UTC by SjonsDePlons

2021-11-24 13:06 UTC, Jarivanoort requested changes
Geen spine

2021-11-24 13:10 UTC, ahoefnagel requested changes

2021-11-24 13:10 UTC, ahoefnagel commented on WobblyStealthGame/Assets/Scripts/Input/ActiveRagdoll/BalanceModule.cs
> +    [SerializeField] public float jumpForce = 100;
Does jump force have to be public? if so, please apply PascalCase.

2021-11-24 13:20 UTC, Jarivanoort approved these changes

2021-11-25 11:39 UTC, ahoefnagel approved these changes

2021-11-25 11:39 UTC, merged