Art chair
Salt-Grain-Studio/WobblyStealthGame pull request #206
Opened 2021-11-25 15:16 UTC by Pedro-Bronsveld

## Changelog
- Added chair model and prefab.
- Added desk lamps models and prefabs.
- Added cactus models and prefabs.
- Added UFO model, prefab, animation, and script.
- Cleared Prefab Preperation Scene.

![2021-11-25 16_09_04-WobblyStealthGame - ArtChairTest - PC, Mac   Linux Standalone - Unity 2020 3 20f](https://user-images.githubusercontent.com/22012835/143466211-fe63b0fe-1427-4102-bbf1-938ecb05c686.png)

2021-11-26 09:10 UTC, Jarivanoort requested changes

2021-11-26 09:10 UTC, Jarivanoort commented on WobblyStealthGame/Assets/Art/Prefabs/UFO/UFO.cs
> +    public float hoverTransitionDuration = 1f;
```suggestion
    [SerializeField] private bool hover = false;
    [SerializeField] private float hoverTransitionDuration = 1f;
```

2021-11-26 09:31 UTC, Jarivanoort approved these changes

2021-11-29 09:29 UTC, ronanhub approved these changes

2021-11-29 09:29 UTC, merged