Added a rotating logo
Salt-Grain-Studio/WobblyStealthGame pull request #214
Opened 2021-11-26 14:55 UTC by Griffin33

2021-11-29 09:28 UTC, Jarivanoort requested changes
![image](https://user-images.githubusercontent.com/32331838/143842039-e6bc9260-c216-46e3-8354-47692e1dfb28.png)
En video kan niet op oldskool computer

2021-11-29 10:20 UTC, ahoefnagel approved these changes

2021-11-29 10:28 UTC, Jarivanoort requested changes
Destructible script is er af, maar kabels blijven nu zweven en video werkt bij mij nog steeds niet maar bij andere wel

2021-11-30 09:47 UTC, MatthijsHofele requested changes
De computer is nu gewoon losse stukjes op de kabels na. Met het destructible script maakten wij van de volledige computer deze losse stukjes. We willen graag dat de OldSkoolComputer een eigen collider heeft waarna wij de kinderen physics geven. Op deze manier is hij al gebroken voordat er een collision mee is

2021-12-02 10:48 UTC, Jarivanoort approved these changes

2021-12-02 11:15 UTC, ronanhub approved these changes
library deleted en boem hij werkt

2021-12-02 11:18 UTC, merged