Added -> Erlenmeyers, OxygenTank, Changed -> Materials, Folder Struct…
Salt-Grain-Studio/WobblyStealthGame pull request #221
Opened 2021-11-29 14:08 UTC by Turboramin

…ure, Fixed -> TestTubes

Erlenmeyer en Oxygentank toegevoegd.

Mappenstructuur aangepast, lab-models verplaatst naar Art/Prefabs/LabStuff.

TestTubes colliders/rigidbody gefixed.

Nieuwe prefabs aangemaakt onder Art/Prefabs/LabStuff.

2021-11-29 14:40 UTC, ronanhub requested changes
![image](https://user-images.githubusercontent.com/45386974/143887283-66019a9d-a68e-4f5e-b218-84fe9b2f72a4.png)
De volgende objecten moeten een convex mesh collider krijgen:
>Testubes
    >TestTube01
    >TestTube02
    >TestTube03
    >TestTubeRack

2021-11-30 09:14 UTC, Turboramin commented
Er wordt gebruik gemaakt van een Box Collider op de TestTubeRack en een RigidBody op de TestTubes zelf, ze vallen goed om het is getest.

![image](https://user-images.githubusercontent.com/43754521/144018638-813cf0e2-7750-4691-852d-5bbf250bb1cb.png)

2021-11-30 09:30 UTC, ronanhub commented
> Er wordt gebruik gemaakt van een Box Collider op de TestTubeRack en een RigidBody op de TestTubes zelf, ze vallen goed om het is getest.
> 
> ![image](https://user-images.githubusercontent.com/43754521/144018638-813cf0e2-7750-4691-852d-5bbf250bb1cb.png)

De testtubes zelf hebben een mesh collider, en die is niet als convex gemarkeerd. Deze moet als convex worden gemarkeerd om te werken met een rigidbody. Of de mesh collider moet worden uitgezet in de testtubes zodat alleen de box collider wordt gebruikt
Anders krijg je errors:
![image](https://user-images.githubusercontent.com/45386974/144021268-3e275c50-3bdb-45f0-a843-e63fdf9d808e.png)

2021-11-30 09:43 UTC, Turboramin commented
Ah zo mb, zal ze eraf halen

2021-11-30 09:56 UTC, ronanhub approved these changes
Testtube colliders zien er nu ook goed uit

2021-11-30 10:20 UTC, merged