Bomb drone
Salt-Grain-Studio/WobblyStealthGame pull request #224
Opened 2021-11-30 11:00 UTC by ahoefnagel

## Added 
- Nuke with particles and explosion on impact configuration. 
- BombDrone 
- Drone manager
- Bomb manager
- Sample textures for nuke explosion

## Changed 
- Wind material

2021-11-30 15:24 UTC, ronanhub commented on WobblyStealthGame/Assets/Scripts/Enemies/DroneManager.cs
> +
```suggestion
```

2021-11-30 15:24 UTC, ronanhub commented on WobblyStealthGame/Assets/Scripts/Enemies/DroneManager.cs
> +
```suggestion
```

2021-11-30 15:25 UTC, ronanhub commented on WobblyStealthGame/Assets/Scripts/Interactables/BombManager.cs
> +
```suggestion
```

2021-11-30 15:25 UTC, ronanhub commented on WobblyStealthGame/Assets/Scripts/Interactables/BombManager.cs
> +
```suggestion
            if (explosionDelay <= 0)
            {
```

2021-11-30 15:26 UTC, ronanhub commented on WobblyStealthGame/Assets/Scripts/Interactables/BombManager.cs
> +
```suggestion
```

2021-11-30 15:26 UTC, ronanhub approved these changes

2021-11-30 15:44 UTC, ronanhub approved these changes

2021-12-01 11:35 UTC, MatthijsHofele requested changes

2021-12-01 11:35 UTC, MatthijsHofele commented on WobblyStealthGame/Assets/Scripts/Enemies/DroneManager.cs
> +    }
bombTimer = bombthrowtimeout+0.01f in Start() zodat hij bij de eerste keer alerten meteen gooit. Nu wacht hij eerst 5 sec

2021-12-01 12:00 UTC, ahoefnagel commented on WobblyStealthGame/Assets/Scripts/Enemies/DroneManager.cs
> +    }
In de laatste commit heb ik dit aangepast, zodat hij nu bij het detecteren gelijk een bom laat vallen

2021-12-01 12:01 UTC, MatthijsHofele approved these changes

2021-12-01 12:24 UTC, ronanhub approved these changes

2021-12-01 12:24 UTC, merged