New main alien import
Salt-Grain-Studio/WobblyStealthGame pull request #229
Opened 2021-11-30 15:15 UTC by SjonsDePlons

2021-11-30 15:34 UTC, MatthijsHofele requested changes
Stengel vliegt alle kanten op

2021-11-30 15:36 UTC, MatthijsHofele approved these changes
Laat maar

2021-11-30 15:40 UTC, ronanhub commented on WobblyStealthGame/Assets/Scripts/Input/ActiveRagdoll/BalanceModule.cs
> +        Torgue,
```suggestion
    private enum Mode
    {
        Torgue,
```
Change torgue -> torque

2021-11-30 15:41 UTC, ronanhub approved these changes

2021-11-30 15:42 UTC, ronanhub requested changes
Change torgue to torque and fix bracket

2021-12-01 09:42 UTC, ronanhub approved these changes

2021-12-01 09:42 UTC, merged