Keycard springy door
Salt-Grain-Studio/WobblyStealthGame pull request #230
Opened 2021-11-30 15:17 UTC by ronanhub

2021-11-30 15:19 UTC, MatthijsHofele requested changes

2021-11-30 15:19 UTC, MatthijsHofele commented on WobblyStealthGame/Assets/Scripts/Interactables/SpringyDoorManager.cs
> +#endif
????

2021-11-30 15:19 UTC, MatthijsHofele commented on WobblyStealthGame/Assets/Scripts/Interactables/SpringyDoorManager.cs
> +        Debug.Log(State);
??????????

2021-12-01 09:35 UTC, MatthijsHofele approved these changes
door go brr

2021-12-01 09:47 UTC, SjonsDePlons approved these changes

2021-12-01 09:47 UTC, merged