Added a stool
Salt-Grain-Studio/WobblyStealthGame pull request #241
Opened 2021-12-01 15:03 UTC by Griffin33

2021-12-02 09:26 UTC, Jarivanoort approved these changes

2021-12-02 09:38 UTC, ronanhub requested changes
![image](https://user-images.githubusercontent.com/45386974/144396082-e551caf3-d37b-40af-9b09-ea4f609b3c96.png)
De mesh collider in Leg moet worden uitgezet
![image](https://user-images.githubusercontent.com/45386974/144396249-493d0569-5cd5-48c4-aa55-55266ef26b5f.png)

2021-12-02 09:40 UTC, Jarivanoort requested changes
zie comment van ronan

2021-12-02 09:40 UTC, ronanhub commented
Misschien kunnen de colliders sowieso simpeler, er hoeven niet 3 colliders per poot te zijn, dat heeft invloed op performance

2021-12-06 11:01 UTC, ronanhub commented
Ik zal er vandaag naar kijken, bedankt voor de change

2021-12-06 14:44 UTC, ronanhub approved these changes

2021-12-06 15:00 UTC, Jarivanoort approved these changes

2021-12-06 15:15 UTC, merged