more sounds
Salt-Grain-Studio/WobblyStealthGame pull request #252
Opened 2021-12-02 13:06 UTC by ronanhub

- Stunsurface
- trampoline
- killerswing
- draaimolen machine

2021-12-02 13:24 UTC, Jarivanoort requested changes

2021-12-02 13:24 UTC, Jarivanoort commented on WobblyStealthGame/Assets/Scripts/Interactables/KillerSwingBehaviour.cs
> +        Debug.Log(hinge.angle);
```suggestion
```

2021-12-02 13:24 UTC, Jarivanoort commented on WobblyStealthGame/Assets/Scripts/Interactables/KillerSwingBehaviour.cs
> +            if (wasPositive && Mathf.Abs(70-hinge.angle) < 25)
```suggestion
            if (wasPositive && Mathf.Abs(70 - hinge.angle) < 25)
```

2021-12-02 13:24 UTC, Jarivanoort commented on WobblyStealthGame/Assets/Scripts/Interactables/KillerSwingBehaviour.cs
> +            if (!wasPositive && Mathf.Abs(70-hinge.angle) < 25)
```suggestion
            if (!wasPositive && Mathf.Abs(70 - hinge.angle) < 25)
```

2021-12-02 13:26 UTC, Jarivanoort approved these changes

2021-12-03 10:15 UTC, ahoefnagel approved these changes

2021-12-03 10:15 UTC, merged