Add: Throw object with F
Salt-Grain-Studio/WobblyStealthGame pull request #276
Opened 2021-12-06 14:40 UTC by SjonsDePlons

## Added
- Throw objects with the F key

## Changed
- sample scene for testing

2021-12-06 14:49 UTC, MatthijsHofele requested changes
Hij heeft een beetje weinig gooikracht. Lijkt me een goed idee om dat variabel te maken voor design

2021-12-06 15:18 UTC, MatthijsHofele approved these changes

2021-12-06 15:55 UTC, Jarivanoort requested changes
![image](https://user-images.githubusercontent.com/32331838/144878519-c4e6b4f2-8935-4dff-905c-17cc54ec78eb.png)

2021-12-07 10:10 UTC, Jarivanoort approved these changes

2021-12-07 10:11 UTC, merged