Art elevator
Salt-Grain-Studio/WobblyStealthGame pull request #297
Opened 2021-12-08 14:57 UTC by Pedro-Bronsveld

## Changelog
- Added elevator and elevator shaft model to elevator prefab.
- Set correct rotation and scale of elevator in concept level.
- Disabled stretching cube thingy in elevator prefab.

https://user-images.githubusercontent.com/22012835/145230145-f77865e3-13db-4bf1-939f-650039018fd2.mp4

https://user-images.githubusercontent.com/22012835/145230280-cab153d9-7737-4c8d-a88d-a71c978ef557.mp4

2021-12-08 15:50 UTC, ronanhub requested changes
De elevator moet ook worden toegevoegd aan de RigidbodyElevator prefab

2021-12-09 13:04 UTC, Pedro-Bronsveld commented
> De elevator moet ook worden toegevoegd aan de RigidbodyElevator prefab

Ik heb hem toegevoegd aan de rigidbidy elevator maar de lift gaat niet meer op en neer nadat ik de lift schacht toevoeg.

Zonder lift schacht:
https://user-images.githubusercontent.com/22012835/145401608-e6e74d78-60cd-4734-b3c0-688a1c1c24f3.mp4

Met liftschacht:
https://user-images.githubusercontent.com/22012835/145401624-f0c6a57a-dcf0-40a8-9dc2-4e0406be8fa4.mp4

2021-12-09 15:39 UTC, ronanhub requested changes
De normale elevator werkt goed
De rigidbody elevator werkt niet, maar ik denk dat iemand van dev daar naar moet kijken

Wel moeten de changes in de conceptpresentatie level er uit, want deze zijn niet aangegeven in het scenes en prefabs kanaal, en zal voor conflicten zorgen

2021-12-10 09:36 UTC, Pedro-Bronsveld commented
Develop gemerged met art-elevator. Concept level in art-elevator overschreven met die van develop.

Geen merge conflicten.

2021-12-10 10:50 UTC, ronanhub approved these changes

2021-12-10 10:54 UTC, Jarivanoort submitted a review, later dismissed

2021-12-10 10:55 UTC, ronanhub requested changes
![image](https://user-images.githubusercontent.com/45386974/145563056-02d01756-5acf-4b84-b7fa-671b1d39018b.png)
De spawn is nu paars in de conceptpresentatie level

2021-12-10 11:04 UTC, ronanhub commented
ik zou de changes in de conceptpresentatie gewoon helemaal weggooien want er is nog een grote change aan die level in een andere branch 
![image](https://user-images.githubusercontent.com/45386974/145564275-e59e2964-4fa9-47a8-ac56-f52427dad5e1.png)

2021-12-13 10:23 UTC, merged