Volume sliders
Salt-Grain-Studio/WobblyStealthGame pull request #354
Opened 2021-12-21 13:44 UTC by ronanhub

2021-12-21 15:25 UTC, Jarivanoort approved these changes
Sliders werken, maar ik heb niet elke sound getest 🙃

2021-12-22 11:07 UTC, SjonsDePlons requested changes
Als ze helemaal links staan kan ik ze niet meer bewegen

2021-12-22 13:08 UTC, ronanhub commented
> Als ze helemaal links staan kan ik ze niet meer bewegen

dit is gefixt

2021-12-22 15:00 UTC, ahoefnagel approved these changes

2021-12-22 15:00 UTC, merged