Level3 designiteratie
Salt-Grain-Studio/WobblyStealthGame pull request #401
Opened 2022-01-11 13:39 UTC by tomlanphen

level 3 aanpassingen

2022-01-11 14:22 UTC, MatthijsHofele requested changes
Alle buttons zijn een beetje fucked. De scale staat op 15x5x15

2022-01-11 14:54 UTC, Turboramin commented
wat is er allemaal aangepast in de scene

2022-01-11 16:00 UTC, Jarivanoort approved these changes

2022-01-12 09:17 UTC, MatthijsHofele requested changes
Lift bij tank kamer staat niet aligned met de vloer

Lasers moeten even recht worden gezet

Veel knoppen zijn nog super plat

2022-01-12 09:54 UTC, merged